resolver: lts-18.10
allow-newer: true

packages:
- '.'

extra-deps:
  - git: https://github.com/incoherentsoftware/sdl2.git
    commit: 1578a635b8882883e5b07557e8a32cb486bde001
  - git: https://github.com/incoherentsoftware/sdl2-image.git
    commit: 1ee72e190b24fe5aa4b9112a3784410d11db130a
  - git: https://github.com/incoherentsoftware/sdl2-ttf-1.git
    commit: 26631ca9347413921ff91137ef192086d93bbb02
  - directory-1.3.6.2
  - hashable-1.3.0.0
  - integer-logarithms-1.0.3.1
  - scientific-0.3.7.0
  - text-1.2.4.1
  - time-1.9.3

flags:
  sdl2:
    no-linear: true

extra-package-dbs: []
